services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: biko
      POSTGRES_PASSWORD: biko
      POSTGRES_DB: biko
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
